/** Versioned so offline audits can distinguish the policy text used by a live decision. */
export const INSTRUCTIONS_VERSION = '2026-09-26-audit-v16';
/**
 * Sent only with search values, so it costs nothing while search is off. It says what the numbers are and how much to
 * trust them: a lookahead that sees multi-turn consequences, but over guessed sets and a simplified engine.
 */
export const SEARCH_INSTRUCTION = 'search on an action is a lookahead by a battle engine that plays about two turns forward over many sampled guesses at the hidden opposing sets, with both sides choosing at once: share is the part of its search that went to the action, score its estimated chance of winning after it. It sees what the one-turn figures miss — switches, recovery, status and lost turns over several turns — but it guesses at sets and simplifies some mechanics. Treat a large share as strong evidence, and depart from it only for a concrete reason the figures above show.';
export const INSTRUCTIONS = [
  'Choose the listed legal action that best advances winning this Gen 9 singles battle. Compare the supplied outcomes, not move names or listed base power. Rank materially different outcomes differently; keep uncertainty where evidence is incomplete, without flattening clearly inferior choices into near ties.',

  'First establish whether this is a forced replacement (stayingInIsNotAnOption). Otherwise read incomingThreatIfWeStayIn, survivalIfWeStayIn and each move\'s turnOrder. An attack that can KO is worthless if we are knocked out before executing it. Threats are conditional on the opponent using those moves, not predictions that it will; do not turn a worst-case threat into a guaranteed incoming action.',

  'Compare actual damageRange and conditionalKO before selecting an attack. ifTheyRecoverBeforeThisHit shows when a revealed recovery move can act first and remove an apparent knockout; this is a conditional reply, not a prediction that they will use it. A slower recoil attack into repeated recovery can drain us even while their HP falls, so compare Rest or another safe way to reset that race. Normally the higher damage is the better attack: moving first is worth little when the target survives either way, so do not trade damage for priority on a target that is not being knocked out. Read priorityTradeoff: if priority does not KO and we survive the modeled incoming hit, favour the stronger executable attack after checking accuracy and effects. Priority is useful when it secures a KO, avoids a concrete disruption, or is our only way to damage before fainting; being slower alone is not a reason to choose weak chip. Modeled survival is conditional, not a guarantee.',

  'The exception is when the target is actually being knocked out. Damage beyond a knockout is surplus and buys nothing, so once two or more moves each show conditionalKO all-sampled-rolls against the current target, stop comparing their damage and choose on what else differs — above all turnOrder, since a knockout that moves first wins the exchange untouched while a bigger one that moves second lets the target act. Recoil, drain, self-switch and a spent Tera are real costs at that point. This applies only between moves that each already show that knockout; it is not a general preference for priority.',

  'Repeated Protect with noIdentifiedPayoff only delays the same losing position at falling success odds; prefer useful damage or a safe switch. Preserve Protect for pending Wish, healing, opposing residual damage, relevant timers or credible PP exhaustion. Check takesNothingFromIt, targetSubstitute and wouldAccomplishNothing before committing to a move. Damage to a Substitute is not HP damage to its holder, and excess single-hit damage does not spill through.',

  'Evaluate recovery, setup, status, weather and Protect on whether their benefit can actually occur. wastedBecauseWeAreKnockedOutFirst, neverGoesOff and executionRisk qualify or negate the optimistic projections beside them. Read effectiveStageChanges and stagesAfter: Contrary reverses listed changes and Simple doubles them. A Contrary Superpower or Leaf Storm can build a win condition; ordinary Superpower weakens later turns, so compare sameMoveDamagePercentOnNextUse instead of repeating it for its original power. Do not automatically switch after a drop when the current attack is still the best trade. A slower setup can be correct if we survive this turn and nextTurnOrderAtEqualPriority becomes ours-first; check worstModeledHPAfterSetupTurn, opposing priority and Trick Room. Choice Scarf and entry Sticky Web are already reflected in effective speed. Stat changes disappear on fainting; status and hazards persist. A possible future boost is not damage this turn. afterThisWeather, substitute, delayedRecovery and afterItsStatChange say what a non-damaging turn actually buys, and a projected gain is only worth its turn if we survive to collect it. No missing estimate and no absent warning means safety.',

  'Compare switches using entry damage, incoming threat, retained HP and ourBestDamageFromNextTurn, which is next turn at the earliest and is not comparable with a move\'s damage this turn. A voluntary switch gives up this turn\'s attack; a forced replacement does not. The opponent chooses before seeing our switch, so takesSwitchTurnAttack, what each switch-in takes from switchTurnAttack aimed at the Pokémon we withdraw, is what it usually absorbs; incomingThreat is the worst case if they anticipate the switch. Treat knockedOutOnEntry as a sacrifice cost, and avoid wouldUndoLastSwitch and the guard warnings unless their stated exception applies, and do not switch repeatedly between the same matchup without gaining something. switchingOutTransformsOurActive is the exception where leaving is itself the gain. Those matchups assume the Pokémon currently out stays; theirBenchThatBeatsIt names what they could bring in on the same turn to win it instead, which is a risk to weigh rather than an expected reply. Uncertain trapping is a risk, not permission to ignore the authoritative legal actions.',

  'switching.onSuccessfulSwitchOut prices the outgoing Pokémon separately from the incoming matchup. Clearing Leech Seed, Salt Cure, Curse, confusion, attraction, Yawn, Perish Song or move restrictions is a real gain, not an empty switch cycle. Avoided residual damage is not restored HP. Compare removal of stat drops, Natural Cure, Regenerator and a reset Choice lock against lost boosts, Substitute and healing effects, entry hazards and the incoming attack. Ordinary switching does not cure persistent status; Toxic resets its counter but remains poison. Only select offered legal switches; trapping can prevent escape and uncertain switches may fail. Baton Pass is not an ordinary switch. thisMatchupSoFar is what the current pairing has actually done since it met; with theyAreNotLosingGround, their recovery, Leftovers or our lost turns are outpacing our damage, so repeating the same attack is not progress — change the plan: a different move (Knock Off removes Leftovers), status, hazards or a switch. Repeated attacks into recovery or Substitute while we drain away are not progress: use repeatedMoveWhileDraining to reconsider the exchange, especially when a legal switch stops the drain. Do not force a switch that loses an immediate win or sacrifices an essential answer.',

  'The Pokémon in front of us is not always the one our move lands on. ifTheySwitch prices each of our moves against the bench Pokémon they might bring in, ranked by the trade a switch is made on and not by any prediction that they will make it. The Pokémon actually out is the default target, so do not give up damage on it for a switch that may not happen. Reach for ifTheySwitch when the choice is otherwise close, when the current target is already settled — a knockout either way, or a target that shrugs the move off either way — or when the likely arrival would blank one of our moves while another catches it. Those numbers exclude the entry hazards it would take, so they are a floor. opponentSwitching is what they have actually done: when they keep switching from this Pokémon to fromThisOneTheyHaveGoneTo, ourMovesIntoIt is likely what our move really does, so do not spend Tera or a self-lowering move such as Overheat into an arrival it does nothing to. When weHaveSwitchedOnEachOfTheLast is set too, each of our entries has paid a hit while nothing was attacked; hitting the likely arrival is usually what breaks that.',

  'Some damage is real but conditional, and it is priced with its condition rather than as a plain number. conditionalDamage covers Counter and Mirror Coat, which return twice the hit they absorb and fail completely if that hit does not land, and Pain Split, which is a heal only while we are the lower of the two. suckerPunch, on Sucker Punch and Thunderclap, gives the share of the target\'s sampled movepool that is an attack at all, because both fail against a status move or a switch. Prefer an unconditional move of similar value; take the conditional one when the unconditional line loses anyway. saltCure and itsSaltCureChipsThemEachTurnPercent are Salt Cure\'s real damage: that share of their max HP at the end of every turn until they switch, a quarter for Water and Steel types, which no boost, recovery or Rest removes — the answer to a Pokémon out-healing or out-boosting our attacks. activatesTheirItem is a cost, not a benefit: do not fire a super-effective move into a possible Weakness Policy holder that it will not knock out when another move gets there, and count Rocky Helmet\'s costsUsPercentOfMaxHP against every contact move, since it is paid on each one and a non-contact move of similar damage avoids it entirely.',

  'When weAreEncored is set our moves have been taken away, not narrowed: staying in hands the opponent free turns for as long as it runs, so switch unless the locked move is doing real work or every replacement is knocked out on the way in. Using Encore ourselves is worth three turns of whatever the opponent just did, which is decisive against a status move and close to nothing against an attack. ourTurnMayBeLost and theirTurnMayBeLost say how often a Pokémon simply does not act, and flinchRisk how often a faster opponent\'s named move stops us; a switch happens before any move and cannot be lost, so when we must leave, switch rather than pivot. These are risks, not resources. Plan on the turn happening and treat the chance it does not as a reason to prefer the safer line; do not stay in on a paralysed or sleeping Pokémon because it might act, and do not count on their paralysis or sleep to save us. The same holds for our own accuracy: a move that can miss, when a miss lets their attack knock out a healthy Pokémon, is not worth it while a switch-in survives their hits and knocks the target out at every roll — endgame beats names who does. A move with crashesForHalfOurHPIf is the one opponents punish: when they can see it coming — we are locked into it, it knocks their Pokémon out, or it is our hardest hit — a Protect they have ready or a switch to a teammate that takes nothing from it (ifTheySwitch, opponentSwitching) costs them nothing, so prefer an attack that cannot crash. Gamble on it only when every alternative already loses — a certain knockout against us next turn, or no move that changes the outcome — and say so by ranking it above the alternatives only then. A sleeping Pokémon with Sleep Talk still acts, with a move picked at random from actsThroughSleepTalk, and whileAsleepItComesAtMostPercent is how likely the switch-turn attack really is; a sleeper without it that cannot wake gives a free switch. Sleep and Truant are the exceptions that are sometimes knowable: chanceItWakesAndMovesThisTurnPercent is zero on the first attempt and reaches 100 once three turns have been lost, Rest is exactly two turns, and truant gives the every-other-turn schedule, so those are facts to use rather than odds to gamble on.',

  'Revival Blessing restores a fainted teammate on the bench to half max HP, not the user. Compare its candidates and their future entry hazards; the user must act before fainting. A revive selection is not a switch. Low HP alone is no reason to preserve or sacrifice a Pokémon: preserve a weakened one only when its later contribution or ability to absorb an attack outweighs saving it now. Deliberate sacrifice can give a free replacement after the opposing attack; fainting to hazards may not absorb that attack, and opponentBoostsOnKnockout makes a sacrifice costly. For pivot moves compare both branches: if they switch, choose our replacement after their arrival; if they stay, a slow pivot can shield our replacement, while a fast pivot exposes it. Account for immunity, failure and contact damage. Do not assume an opposing switch merely because it is possible.',

  'Use endgame as a coarse matchup guide, not a win forecast: preserve a necessary remaining answer. soleDurableInto names a teammate that alone takes a small modeled hit from a revealed opponent even when the strict damage race says it loses; preserving that teammate can matter after the opponent is chipped. In a one-on-one finish do not trade an immediate winning move for a switch target\'s next-turn damage. Price hazards only when future opposing entries remain. Spend Tera for a concrete gain shown in defensiveTera, teraBuysUs or teraChangesOurForme, never for a small redundant damage increase, and count its costs: a defensiveTera with makesUsWeakerToTheirAttack, and the teammates in teraIsAlsoNeededBy, who lose it for the rest of the battle; changesOurForme can reach the same typing without spending it. opponentChoiceLock and ourChoiceLock name the move each side is committed to until it switches.',

  'All numeric envelopes and KO labels are conditional on the modelled sets and mechanics; respect coveredProbabilityMass, unknowns, survival effects, accuracy, opposing switches and Tera. Damage and KO labels assume the move lands: knockoutOnlyIfItHits gives the real chance of our knockout once accuracy is counted, accuracyPercent marks an opposing move that can miss, and knockedOutOnEntry is only claimed for a knockout that cannot miss — knockedOutOnEntryIfItHits names the move and its odds otherwise. Set frequencies describe how sets are generated, not what the opponent will choose. Select only a listed action ID, and give a valid probability distribution with the chosen action maximal. Runtime guards may skip a conditionally dominated move or a self-defeating switch; rank the viable alternatives meaningfully.',
].join('\n');

/**
 * Paragraphs that explain a field only some decisions carry, sent only with that field. Sent always, the two added for
 * Trick and for reactive abilities put about 1.4 KB on every payload and pushed one decision in five from the reduced
 * tier to the minimal one, which drops the switch-in predictions, projections and opposing set detail.
 */
export const CONDITIONAL_INSTRUCTIONS: Record<string, string> = {
  // Only forced replacements carry it; always sending it cost every other payload 340 bytes of budget.
  ifTerastallizedOnFirstMoveAfterReplacement: 'After a fainted ally\'s free replacement, ifTerastallizedOnFirstMoveAfterReplacement shows a separate next-turn line: that Pokemon can spend our still-available Tera before the opponent attacks, and it may remove an apparent knockout. Tera is not used by the replacement action itself; compare the saved matchup with the once-per-battle cost.',
  crashesIfTheyTerastallizeInto: 'crashesIfTheyTerastallizeInto on a crash move lists their unspent Tera types that are immune to it and the share of their sets carrying one. Tera happens before any move, so if they use it this move hits nothing and we lose half our max HP; that risk is on top of accuracy and Protect.',
  theyMayEncoreUsFirst: 'theyMayEncoreUsFirst means their Encore is likely and would land before our move this turn: whatever move we pick is replaced by locksUsInto, for three turns, and choosing a different move does not avoid it. Only a switch does, because the Pokémon coming in has no last move to lock. thatMoveNowFails, itIsImmune or thatMoveIsAStatusMove mean those turns are wasted; weigh that at encoreChancePercent against what switching costs.',
  phaze: 'phaze on Roar, Whirlwind, Dragon Tail or Circle Throw says what forcing their active out does. erasesTheirStatChanges is every stage it loses, drops included; dragsInAtRandom is who can replace it, chosen at random rather than by the opponent; theReplacementEntersInto is our hazards it takes on entry. These moves go last (priority -6), so the phaze happens only if we are still in after their move. Weigh a boosted opponent\'s next hits at those stages against the boosts lost, not only against this turn\'s damage. noDrag says why nothing is forced out.',
  sharedByEveryActionBelow: 'sharedByEveryActionBelow holds fields that every action carrying them had identically, stated once instead of repeated: read each as present on those actions.',
  sameAsWithoutTerastallising: 'An action with sameAsWithoutTerastallising is the named action plus Terastallising: every field not written out is identical to that action, the fields written out are what the Tera changes, fieldsThatNoLongerApply lists what it removes, and nothingModelledChangesByTerastallising means it buys no measured gain. It is a separately selectable action.',
  strongerImmediateDamageAvailable: 'strongerImmediateDamageAvailable names an attack whose smallest roll beats this one\'s largest. Compare effects, accuracy, PP and turn order before choosing; higher damage alone is not strict dominance.',
  choiceItemTrick: 'choiceItemTrick is the value of Trick or Switcheroo beyond this turn\'s zero damage. Giving a Choice item before the opponent acts can lock the setup or recovery move it chooses, and taking Leftovers removes its continuing recovery. If they switch, the item goes to the incoming Pokémon instead: use ifTheyRepeatObservedSwitch alongside opponentSwitching to judge that trade. Losing our Choice item frees our other moves when the received item is not another Choice item. Do not assume the opponent stays, or that a move it used before receiving the item was locked. A repeated two-Pokémon switch route that spends our HP while the opponent heals is losing ground; change the move or the route instead of sending the same low-HP answer around again.',
  triggersTheirAbility: 'triggersTheirAbility shows what our hit gives the opponent. Weak Armor triggers on a physical hit even without contact: a surviving target gains two Speed stages per hit, so check whether it can now sweep before choosing chip or a multi-hit attack. Stamina, Cotton Down and Cursed Body also need no contact. Contact can additionally cost HP, status, Speed, an item or our ability; compare a non-contact attack when it achieves the same result. A certain knockout still removes the Weak Armor threat, and a possible ability retains only its listed probability. opponentBoostsOnKnockout includes Soul-Heart, which gains Special Attack from any faint while it is active, including our recoil or poison faint.',
  berryRecoveryAfterHit: 'berryRecoveryAfterHit prices Sitrus Berry on a surviving target: the first berry heals 25% after our hit drops it to half HP. Harvest can grow the berry back at the end of this turn, and if still at or below half HP it is eaten again for another 25%. The search engine omits Harvest regrowth, so use these ranges over its score for this interaction, especially before a move that faints our own Pokémon. The ranges apply only if the attack lands and the target survives.',
};
/** The instructions for one payload: the standing text, the search note when search values are present, and each conditional paragraph whose field appears. */
export function instructionsFor(state: unknown, withSearch: boolean) {
  const text = JSON.stringify(state) ?? '';
  const extra = Object.entries(CONDITIONAL_INSTRUCTIONS).filter(([field]) => text.includes(`"${field}":`)).map(([, paragraph]) => paragraph);
  return [INSTRUCTIONS, ...(withSearch ? [SEARCH_INSTRUCTION] : []), ...extra].join('\n');
}
